In [1]:
import math
import numpy as np

Đặt seed ngẫu nhiên

In [2]:
np.random.seed(1000)

Khởi tạo 10 điểm dữ liệu 3 chiều ($x$, $y$, $z$) ($0 \leq x, y, z, \leq 100$)

In [3]:
x = np.random.uniform(low=0, high=101, size=(10, 3))

Với $\phi(\bold{x})=\bold{x}$, ta sử dụng kernel tuyến tính là tích vô hướng giữa hai vector đầu vào:
$$\phi(\bold{x})^T \phi(\bold{y})=\bold{x}^T \bold{y}=\bold{K}(\bold{x}, \bold{y})$$

In [4]:
K = np.matmul(x, x.T)

In [5]:
K

array([[13704.46679126,  6296.79183156,  2997.35003572, 13052.43405066,
        10036.16595525, 10737.36549282,  6976.50337546, 13796.40731964,
        10742.71095275, 10651.60383694],
       [ 6296.79183156, 10596.85520684,  4240.28505248,  7591.63273839,
         5161.55541554, 10285.29684345,  8340.29719171,  9383.93280487,
         3944.52088082, 11247.74229147],
       [ 2997.35003572,  4240.28505248,  2180.68138949,  2954.33673607,
         2669.58849178,  5881.649496  ,  2138.8429701 ,  3464.58313047,
         2326.00506182,  4693.04312419],
       [13052.43405066,  7591.63273839,  2954.33673607, 13288.55250727,
         9383.79349688,  9682.96483925,  9092.43451958, 14502.1415315 ,
         9657.60475797, 11457.65472879],
       [10036.16595525,  5161.55541554,  2669.58849178,  9383.79349688,
         7547.24208592,  9150.03215185,  4717.10303849,  9920.03484053,
         7998.3937316 ,  8255.47644716],
       [10737.36549282, 10285.29684345,  5881.649496  ,  9682.96483925,
   

Ta sử dụng Gaussian kernel, hay còn được gọi là Gaussian radial basis function (RBF) kernel, được định nghĩa là:
$$\bold{K}(\bold{x}, \bold{y})=\exp\Bigg\lbrace-\dfrac{\lVert \bold{x} - \bold{y} \rVert^2}{2 \sigma^2}\Bigg\rbrace$$
Ma trận $\lVert \bold{x} - \bold{y} \rVert^2$ được tính:

In [6]:
dist_matrix = x[:, np.newaxis, :] - x[np.newaxis, :, :]

square_dist_matrix = np.sum(dist_matrix**2, axis=2)

Ma trận:

$$K(\bold{x}, \bold{y})=\exp\Bigg\lbrace-\dfrac{\lVert \bold{x} - \bold{y} \rVert^2}{2 \sigma^2}\Bigg\rbrace$$

In [7]:
sigma = 100

In [8]:
K = np.exp(-square_dist_matrix/(2*sigma**2))

In [9]:
K

array([[1.        , 0.55689035, 0.6098621 , 0.95656402, 0.94273614,
        0.62087156, 0.5955589 , 0.89491887, 0.9500083 , 0.74377663],
       [0.55689035, 1.        , 0.80666378, 0.64719534, 0.6763468 ,
        0.69318572, 0.79732331, 0.6724086 , 0.56229819, 0.92217516],
       [0.6098621 , 0.80666378, 1.        , 0.62000482, 0.80297048,
        0.67976144, 0.65322623, 0.56664892, 0.7285013 , 0.72929183],
       [0.95656402, 0.64719534, 0.62000482, 1.        , 0.90175683,
        0.57048101, 0.75136317, 0.98053879, 0.8702285 , 0.82315257],
       [0.94273614, 0.6763468 , 0.80297048, 0.90175683, 1.        ,
        0.72072103, 0.64640193, 0.8262993 , 0.98230341, 0.79631056],
       [0.62087156, 0.69318572, 0.67976144, 0.57048101, 0.72072103,
        1.        , 0.3959847 , 0.54477212, 0.65892487, 0.76761078],
       [0.5955589 , 0.79732331, 0.65322623, 0.75136317, 0.64640193,
        0.3959847 , 1.        , 0.7878017 , 0.55592292, 0.78547081],
       [0.89491887, 0.6724086 , 0.5666489

Ta sử dụng kernel đa thức, được định nghĩa là:

$$\bold{K}(\bold{x}, \bold{y})=(r+\gamma\bold{x}^T\bold{y})^d$$

In [22]:
r = 1
gamma = 1
d = -1/2

In [23]:
K = (r + gamma * np.matmul(x, x.T))**d

In [24]:
K

array([[0.00854187, 0.01260102, 0.01826244, 0.00875261, 0.00998147,
        0.00965008, 0.01197154, 0.00851337, 0.00964768, 0.00968885],
       [0.01260102, 0.00971384, 0.01535505, 0.01147635, 0.01391771,
        0.00985985, 0.01094922, 0.01032249, 0.01592017, 0.00942862],
       [0.01826244, 0.01535505, 0.02140939, 0.01839486, 0.01935069,
        0.01303808, 0.02161768, 0.01698681, 0.0207301 , 0.01459575],
       [0.00875261, 0.01147635, 0.01839486, 0.00867451, 0.01032257,
        0.01016186, 0.01048663, 0.00830365, 0.0101752 , 0.00934186],
       [0.00998147, 0.01391771, 0.01935069, 0.01032257, 0.01151005,
        0.01045358, 0.01455849, 0.01003972, 0.01118076, 0.01100532],
       [0.00965008, 0.00985985, 0.01303808, 0.01016186, 0.01045358,
        0.00760201, 0.01459354, 0.00969779, 0.01060934, 0.00885017],
       [0.01197154, 0.01094922, 0.02161768, 0.01048663, 0.01455849,
        0.01459354, 0.00970616, 0.00954455, 0.01613767, 0.01017835],
       [0.00851337, 0.01032249, 0.0169868

Ta sử dụng sigmoid kernel được định nghĩa là:

$$\bold{K}(\bold{x}, \bold{y})=\tanh(r + \gamma \bold{x}^T \bold{y})$$

In [33]:
r = 0.1
gamma = 0.0001

In [34]:
K = np.tanh(r + gamma * np.matmul(x, x.T))

In [35]:
K

array([[0.89966263, 0.62286904, 0.3797222 , 0.88647978, 0.80179435,
        0.82546633, 0.66272113, 0.90140066, 0.82563657, 0.82271451],
       [0.62286904, 0.82093737, 0.48080323, 0.69582632, 0.54844562,
        0.81051545, 0.73246716, 0.7772528 , 0.45774284, 0.84105685],
       [0.3797222 , 0.48080323, 0.30775908, 0.37603507, 0.35132879,
        0.59680184, 0.30396665, 0.41898339, 0.32085551, 0.51484818],
       [0.88647978, 0.69582632, 0.37603507, 0.89143177, 0.77724728,
        0.78881856, 0.76544892, 0.91382082, 0.78785862, 0.84709194],
       [0.80179435, 0.54844562, 0.35132879, 0.77724728, 0.69352946,
        0.76782348, 0.51661423, 0.79760822, 0.71621965, 0.7285113 ],
       [0.82546633, 0.81051545, 0.59680184, 0.78881856, 0.76782348,
        0.94985429, 0.5149527 , 0.82207876, 0.75664967, 0.8801929 ],
       [0.66272113, 0.73246716, 0.30396665, 0.76544892, 0.51661423,
        0.5149527 , 0.82148389, 0.83292499, 0.4493525 , 0.78763136],
       [0.90140066, 0.7772528 , 0.4189833